Adding coverage to digest for parser
google/oss-fuzz pull request #10149
Opened 2023-04-22 08:26 UTC by sg3-141-592

This additional fuzzer `fuzz_params` calls the `digest` utility mocking the stdin and parser args inputs. This is closer to how this utility is used normally and gives additional coverage.

This has shook out an issue pretty quickly https://github.com/bmc/digest/issues/4 .

Another issue, the introspector doesn't seem to be able to measure any coverage on digest at all.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/5122866/233772534-976599e4-42dc-4c08-aacd-2a06db0fb177.png">

2023-04-23 22:58 UTC, DavidKorczynski commented
> Another issue, the introspector doesn't seem to be able to measure any coverage on digest at all.

Can you please post stuff like this on https://github.com/ossf/fuzz-introspector/issues rather than here, as it's just going to be lost down the line if we have these things in PRs rather than issues on right repo.

2023-04-24 22:09 UTC, DavidKorczynski requested changes

2023-04-24 22:09 UTC, DavidKorczynski commented on projects/digest/fuzz_params.py
> +    atheris.Setup(sys.argv, TestOneInput, enable_python_coverage=True)
No need for `enable_python_coverage`

2023-04-25 05:48 UTC, sg3-141-592 commented on projects/digest/fuzz_params.py
> +    atheris.Setup(sys.argv, TestOneInput, enable_python_coverage=True)
Removed `enable_python_coverage`

2023-04-25 05:51 UTC, sg3-141-592 commented
Understood on putting the missing coverage onto issues for introspector. This library is entirely in an `__init__.py` file so it's likely fixed by https://github.com/ossf/fuzz-introspector/pull/1005 . I'll wait for the introspector to be bumped in oss-fuzz to confirm.

2023-04-25 10:10 UTC, DavidKorczynski requested changes
I don't think this fuzzer is really needed as it's kinda superficial. The library is so small https://github.com/bmc/digest/blob/master/digest/__init__.py and the logic is already covered -- don't see any reason for calling by way of `main` from a code analysis perspective

2023-04-25 12:33 UTC, sg3-141-592 commented
Sure, I'm happy to leave it up to you what you do with it.

Hitting the `main` using mocked `stdin` and `argv` means you get more coverage than hitting `digest` directly. But you're right this is very superficial, it's just a lightweight wrapper for `hashlib` so fuzzings not going test much.

2023-04-26 01:39 UTC, Alan32Liu commented
Hope you won't mind me converting it to a draft for now until we have a decision (merge or close): )

2023-04-26 13:16 UTC, DavidKorczynski commented
Closing this due to the reasons mentioned above.

2023-04-26 13:16 UTC, closed without merging