Initial project skeleton for icalendar
google/oss-fuzz pull request #10832
Opened 2023-08-12 19:53 UTC by ennamarie19

This is my first contribution to OSS-Fuzz! I would greatly appreciate any feedback and confirmation that I have configured my project.yaml correctly. 

Thank you for your time and review!

2023-08-12 20:14 UTC, ennamarie19 commented
I believe this project is important because it is used for parsing and generating iCalendar files following the standards in RFC 2445 and RFC 5545. This repository answers the need outlined in RFC2245 of "providing and deploying interoperable calendaring and scheduling services for the Internet." Instead of having to create ad-hoc tools to parse and generate iCalendar files, this Python repository provides an encompassing yet simple means to do so. In other words, icalendar allows for interoperability between calendar services and protocols. With nearly 900 stars on GitHub, this package has a wide user base and has spawned other popular projects such as icalevents.

2023-08-16 11:48 UTC, jonathanmetzman requested changes

2023-08-16 11:48 UTC, jonathanmetzman commented on projects/icalendar/Dockerfile
> +RUN git clone --depth 1 <git_url> icalendar     # or use other version control
Oh please fill this part in.

2023-08-16 11:48 UTC, jonathanmetzman commented on projects/icalendar/build.sh
> +# build project
If you don't want to actually write code at this moment, just delete the build.sh and Dockerfile and leave the project.yaml, but if we do commit them, they have to work.

2023-08-16 11:49 UTC, jonathanmetzman commented
We approve of adding this project. The PR needs a little work though

2023-08-26 22:53 UTC, ennamarie19 commented
@jonathanmetzman I have just finalized my initial integration. I would greatly appreciate your review! :)

2023-08-29 02:14 UTC, jonathanmetzman approved these changes
lgtm

2023-08-29 03:08 UTC, merged