xmldom: accept new project
google/oss-fuzz pull request #11036
Opened 2023-09-28 19:34 UTC by karfau

2023-09-28 21:06 UTC, karfau commented
I'm quite new to the fuzzing topic, testing it locally right now, and maybe that's good enough, since for js there is only one kind of fuzzer possible. ONce I decided I will close or push to the PR.

2023-09-28 22:23 UTC, DavidKorczynski commented
Could you list some of the more prominent users of xmldom and what makes it a security critical project?

2023-09-29 05:48 UTC, karfau commented
Thx for asking, as far as I'm aware it's the most mature library for parsing xml in the NodeJs ecosystem.

- https://github.com/aws/jsii -> https://deps.dev/npm/jsii-pacmak and https://deps.dev/npm/jsii-rosetta which are used as part of building the aws-cdk for differnt languages

Several libraries related to SAML/soap:
- https://deps.dev/npm/xml-crypto -> https://deps.dev/npm/xml-crypto/4.1.0/dependents
- https://deps.dev/npm/xml-encryption -> https://deps.dev/npm/xml-encryption/3.0.2/dependents
- https://deps.dev/npm/x2js -> https://deps.dev/npm/x2js/3.4.4/dependents

The most prominent library for dealing with plist files depends on it
- https://deps.dev/npm/plist -> https://deps.dev/npm/plist/3.1.0/dependents

And some "apps"
- https://github.com/jitsi/jitsi-meet
- https://github.com/futurepress/epub.js

some "dev tools"
- https://github.com/mswjs/msw -> https://deps.dev/npm/msw
- https://github.com/electron/electron-packager
- https://github.com/electron/forge
- https://github.com/auth0/react-native-auth0

Is that enough information?

2023-09-29 09:58 UTC, karfau commented
And just to make sure I'm on the right track:
I created a fuzz target that already found some stuff, I fixed that locally and now it's running for quite a while without finding anything new.

That setup would be something I could setup to run as part of this project and it would run twice a day for a limited time and create a github issue in case it find an issue, which is more likely because it uses a different see each time but preserves the corpus of previous runs, right?

2023-09-29 19:28 UTC, jonathanmetzman commented
> And just to make sure I'm on the right track: I created a fuzz target that already found some stuff, I fixed that locally and now it's running for quite a while without finding anything new.
> 
> That setup would be something I could configure to run as part of this project and it would run twice a day for a limited time 

It will run continuously on our infra. If you think that's wasteful you can manage a [ClusterFuzzLite](https://github.com/google/clusterfuzzlite) setup on github actions

>and create a github issue in case it finds an issue, which is more likely because it uses a different seed each time but preserves the corpus of previous runs, right?

Yes. Note that github issues are really pointers to the issues we file in our bug tracker that has access control so not everyone can see the bug (this makes most sense for e.g. use after free bugs in C++)

2023-09-29 19:28 UTC, jonathanmetzman commented
We accept this project. Let me know if you want me to merge this PR.

2023-10-01 20:55 UTC, karfau commented
That is great news.

For now I put priority on fixing the issues found by the tool when running it locally.

I want to avoid being "flooded" by issues in the start, without being able to resolve them in a timely manner.

Afterwards I will find a way to provide the basic corpus for getting started that I'm currently using. (Is it common for people to add that to the docker image?)

So I marked the PR as a draft for now.

2023-10-09 05:47 UTC, karfau commented
I think the current configuration should already work as expected.
It is currently cloning a specific branch, since I'm struggling with the regression tests for the targets in the project repository.
I think I will split the regression test part into a separate PR/branch in order to unblock this PR and drop the branch from the clone, but I would already love to get some feedback on what I have done so far.
Thx

2023-10-11 05:47 UTC, karfau commented
The fuzz target regression test integration in the source repo is finished, so the Dockerfile no longer clones a branch.

From my perspective this PR is ready, unless I receive some feedback.
Thx

2023-10-11 11:01 UTC, karfau commented
The "libfuzzer, coverage" job looks like what I expected/anticipated, but there are multiple other jobs that are marked as required, which are failing.

I have no clue what I need to do regarding those. I had the impression that I followed all the steps from the docs/instructions

2023-10-11 14:46 UTC, DavidKorczynski requested changes
Could you try and add the following to `project.yaml`:
```
fuzzing_engines:
- libfuzzer
sanitizers:
- none
```

I think missing this is what's causing the build issues.

2023-10-11 15:36 UTC, karfau commented
Makes sense, thx for the hint, I think for some reason the init command didn't apply the javascript defaults, I guess I had a typo.

Done

2023-10-11 15:47 UTC, DavidKorczynski commented
> I think for some reason the init command didn't apply the javascript defaults
> 


Did you use `python3 infra/helper.py generate ...` to create the initial set up? I can see it doesn't provide this although it definitely should set the settings accurately since it's always required.

2023-10-11 15:49 UTC, DavidKorczynski approved these changes

2023-10-11 15:49 UTC, merged

2023-10-11 15:52 UTC, karfau commented
I'm pretty sure I did.
I was also surprised afterwards since the Dockerfile was not using the javascript base image after the command. Needed to figure out tge details using the docs.

2023-10-11 16:34 UTC, karfau commented
Is there some way to see those things running?
I would like to better understand what is happening with this config.

2023-10-12 09:23 UTC, karfau commented
It looks like the build failed because it was not able to find the corpus directory that I added to the docker image.
I will need help to understand how to fix this.

Whe I tested the doker image locally I did run the targets inside the container, but it looks like this is not what is happening over there.

The `xmltest` directory which can not be found is what I extract the corpus to.

What is the proper way to provide a corpus in that setup?

https://oss-fuzz-build-logs.storage.googleapis.com/index.html#xmldom

```
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: performing bad build checks for /tmp/not-out/tmp3icbd7qq/dom-parser.xml.target
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: performing bad build checks for /tmp/not-out/tmp3icbd7qq/dom-parser.html.target
Step #4 - "build-check-libfuzzer-none-x86_64": Retrying failed fuzz targets sequentially 2
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: performing bad build checks for /tmp/not-out/tmp3icbd7qq/dom-parser.xml.target
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: performing bad build checks for /tmp/not-out/tmp3icbd7qq/dom-parser.html.target
Step #4 - "build-check-libfuzzer-none-x86_64": Broken fuzz targets 2
Step #4 - "build-check-libfuzzer-none-x86_64": ('/tmp/not-out/tmp3icbd7qq/dom-parser.xml.target', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmp3icbd7qq/dom-parser.xml.target'], returncode=1, stdout=b'BAD BUILD: /tmp/not-out/tmp3icbd7qq/dom-parser.xml.target seems to have either startup crash or exit:\n/tmp/not-out/tmp3icbd7qq/dom-parser.xml.target -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null\nINFO: New number of coverage counters 1024\nINFO: New number of coverage counters 2048\nINFO: using inputs from: xmltest\nERROR: The required directory "xmltest" does not exist\n', stderr=b''))
Step #4 - "build-check-libfuzzer-none-x86_64": BAD BUILD: /tmp/not-out/tmp3icbd7qq/dom-parser.xml.target seems to have either startup crash or exit:
Step #4 - "build-check-libfuzzer-none-x86_64": /tmp/not-out/tmp3icbd7qq/dom-parser.xml.target -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: New number of coverage counters 1024
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: New number of coverage counters 2048
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: using inputs from: xmltest
Step #4 - "build-check-libfuzzer-none-x86_64": ERROR: The required directory "xmltest" does not exist
Step #4 - "build-check-libfuzzer-none-x86_64": 
Step #4 - "build-check-libfuzzer-none-x86_64": ('/tmp/not-out/tmp3icbd7qq/dom-parser.html.target', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmp3icbd7qq/dom-parser.html.target'], returncode=1, stdout=b'BAD BUILD: /tmp/not-out/tmp3icbd7qq/dom-parser.html.target seems to have either startup crash or exit:\n/tmp/not-out/tmp3icbd7qq/dom-parser.html.target -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null\nINFO: New number of coverage counters 1024\nINFO: New number of coverage counters 2048\nINFO: using inputs from: xmltest\nERROR: The required directory "xmltest" does not exist\n', stderr=b''))
Step #4 - "build-check-libfuzzer-none-x86_64": BAD BUILD: /tmp/not-out/tmp3icbd7qq/dom-parser.html.target seems to have either startup crash or exit:
Step #4 - "build-check-libfuzzer-none-x86_64": /tmp/not-out/tmp3icbd7qq/dom-parser.html.target -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: New number of coverage counters 1024
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: New number of coverage counters 2048
Step #4 - "build-check-libfuzzer-none-x86_64": INFO: using inputs from: xmltest
Step #4 - "build-check-libfuzzer-none-x86_64": ERROR: The required directory "xmltest" does not exist
Step #4 - "build-check-libfuzzer-none-x86_64": 
Step #4 - "build-check-libfuzzer-none-x86_64": ERROR: 100.0% of fuzz targets seem to be broken. See the list above for a detailed information.
Step #4 - "build-check-libfuzzer-none-x86_64": ********************************************************************************
Step #4 - "build-check-libfuzzer-none-x86_64": Build checks failed.
Step #4 - "build-check-libfuzzer-none-x86_64": To reproduce, run:
Step #4 - "build-check-libfuzzer-none-x86_64": python infra/helper.py build_image xmldom
Step #4 - "build-check-libfuzzer-none-x86_64": python infra/helper.py build_fuzzers --sanitizer none --engine libfuzzer --architecture x86_64 xmldom
Step #4 - "build-check-libfuzzer-none-x86_64": python infra/helper.py check_build --sanitizer none --engine libfuzzer --architecture x86_64 xmldom
Step #4 - "build-check-libfuzzer-none-x86_64": ********************************************************************************
Finished Step #4 - "build-check-libfuzzer-none-x86_64"
ERROR
ERROR: build step 4 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```