openvpn: fix build
google/oss-fuzz pull request #12208
Opened 2024-07-12 21:41 UTC by tyler92

Fuzzing of OpenVPN project has not been working for more than a year: https://oss-fuzz-build-logs.storage.googleapis.com/log-ffdb922b-8051-478a-80aa-1f1b0bc3d385.txt . This PR fixes it with the following changes:

1. `crypto_patch.txt` was removed - it wasn't used but the `git apply` command failed. I assume the intention was to test `crypto.c` but I believe there is a better way to do it without patching the source code.
2. Obsolete functions were removed (e.g. `get_auth_challenge`)
3. Existing targets were updated according to the latest changes in the OpenVPN project
4. Memory-related bugs were fixed in several targets (e.g. dereferencing a non-initialized pointer).

2024-07-17 20:23 UTC, tyler92 commented
@DavidKorczynski probably you can have a look, I noticed that you fixed the OpenVPN build previously

2024-07-17 20:34 UTC, DavidKorczynski commented
> 1. `crypto_patch.txt` was removed - it wasn't used but the `git apply` command failed. I assume the intention was to test `crypto.c` but I believe there is a better way to do it without patching the source code.

Could you address this point?

2024-07-17 20:34 UTC, DavidKorczynski requested changes
left a question above

2024-07-17 20:49 UTC, tyler92 commented
> > 1. `crypto_patch.txt` was removed - it wasn't used but the `git apply` command failed. I assume the intention was to test `crypto.c` but I believe there is a better way to do it without patching the source code.
> 
> Could you address this point?

There was a patch `crypto_patch.txt` that modified `crypto.c` file in the OpenVPN's source code. But fuzzer for `crypto.c` is not included in the build. This means the command `git apply crypto_patch.txt` doesn't make sense but causes the build process to fail. This PR includes fixes for all fuzzing targets included in the build.sh. Extending fuzzing targets with `crypto.c` makes sense but I'd rather do it separately because it can be quite difficult to do, if not impossible. Or do you insist on fixing `crypto.c` right now?

2024-11-21 00:02 UTC, DonggeLiu commented
Gentle ping @DavidKorczynski, which would you prefer?

2025-05-14 05:19 UTC, closed without merging