[tarantool] Enable aarch64
google/oss-fuzz pull request #12288
Opened 2024-07-29 13:08 UTC by ligurio

2024-07-29 20:44 UTC, DavidKorczynski approved these changes

2024-07-29 20:46 UTC, DavidKorczynski requested changes
Just confirming the change in the `primary_contact` is intentional?

2024-07-30 06:34 UTC, ligurio commented
> Just confirming the change in the `primary_contact` is intentional?

Yes. Kirill has left the project and in fact, I am responsible for Tarantool fuzzing.

2024-07-30 10:12 UTC, DavidKorczynski approved these changes

2024-07-30 10:12 UTC, merged