micronaut: Build with existing fuzz tests
google/oss-fuzz pull request #12773
Opened 2024-11-26 16:21 UTC by yawkat

Initial fuzz build with the existing targets we have at https://github.com/micronaut-projects/micronaut-fuzzing . I tried to keep as much of the build infra in our repos as possible, including the build.sh.

I've tested locally (build_image, build_fuzzers, check_build, run_fuzzer) and it works.

2024-11-27 12:53 UTC, DavidKorczynski requested changes

2024-11-27 12:53 UTC, DavidKorczynski commented on projects/micronaut/Dockerfile
> +# Copyright 2021 Google LLC
could you set the year to 2024?

2024-11-27 12:53 UTC, DavidKorczynski commented on projects/micronaut/Dockerfile
> +WORKDIR $SRC
$SRC is already the default so no need to set it here

2024-11-27 12:58 UTC, yawkat commented on projects/micronaut/Dockerfile
> +# Copyright 2021 Google LLC
Done

2024-12-10 11:10 UTC, DavidKorczynski approved these changes

2024-12-10 11:10 UTC, merged