yaml-cpp: initial integration
google/oss-fuzz pull request #12853
Opened 2024-12-14 17:37 UTC by initializedd

Initial integration support for a popular C++ YAML library.

2024-12-14 17:54 UTC, DavidKorczynski requested changes
Are maintainers on board with this? I remember the project was approached previously: https://github.com/jbeder/yaml-cpp/issues/963

2024-12-14 18:07 UTC, initializedd commented
> Are maintainers on board with this? I remember the project was approached previously: [jbeder/yaml-cpp#963](https://github.com/jbeder/yaml-cpp/issues/963)

I have not approached the maintainers of yaml-cpp.
Although, I believe it should be fine since the project is covered under the MIT license agreement.

2024-12-14 19:36 UTC, DavidKorczynski commented
we need maintainer approval that they are happy to receive and fix bugs

2024-12-14 19:43 UTC, initializedd commented
> we need maintainer approval that they are happy to receive and fix bugs

I will open an issue on the yaml-cpp repository and reference this PR.

2024-12-17 15:30 UTC, DavidKorczynski commented
> I can't commit to fixing all bugs that OSS-Fuzz comes out with, but I can commit to reviewing any PRs that fix those bugs. @initializedd, would you be willing to commit to (at least trying to) fix bugs?

The caveat here is that the bugs found are following the Google disclosure policy, which means they will be publicised after 90 days if not fixed (and will be made public once they are fixed too if pre the 90 day deadline).

2024-12-18 00:49 UTC, initializedd commented
> @initializedd, would you be willing to commit to (at least trying to) fix bugs?

I am definitely happy to commit to fixing bugs.

@DavidKorczynski In that case, I assume I would need to add myself to `auto_ccs` to receive notifications of bugs that have been discovered?

2025-01-02 02:52 UTC, DonggeLiu commented
> I am definitely happy to commit to fixing bugs.

In that case, the panel is happy to approve this integration.
Thanks @initializedd!

2025-01-02 02:52 UTC, DonggeLiu approved these changes

2025-01-02 02:56 UTC, DonggeLiu commented
@initializedd could you please help update the year in header license?
Thanks and sorry about the delay.

2025-01-02 22:14 UTC, initializedd commented
> @initializedd could you please help update the year in header license to pass the CI check? Thanks and sorry about the delay.

I have updated the copyright year in my latest commit.
Thanks a lot @DonggeLiu!

2025-01-22 05:13 UTC, DonggeLiu commented
The panel has approved.
Thanks for your commitments to fixing bugs!

2025-01-22 05:13 UTC, DonggeLiu approved these changes

2025-01-22 18:51 UTC, initializedd commented
> The panel has approved. Thanks for your commitments to fixing bugs!

Thanks, that is great news!

Although @DonggeLiu, I am slightly confused as to why you seemingly merged google/oss-fuzz into this merge request, rather than the opposite? 

Could you elaborate on what this is achieving, or whether it was an accident?
Please see the commit history for this merge request for more details.

I am happy to drop the merge commit that was made if it was an accident.

2025-01-22 23:19 UTC, merged