Adds python project requests
google/oss-fuzz pull request #4918
Opened 2021-01-05 16:57 UTC by catenacyber

Need to move the fuzz target to the upstream repository

2021-01-05 17:30 UTC, jonathanmetzman commented on projects/requests/build.sh
> +# Copyright 2020 Google Inc.
Google LLC.

2021-01-05 17:30 UTC, jonathanmetzman commented on projects/requests/build.sh
> +# Copyright 2020 Google Inc.
2021

2021-01-05 17:30 UTC, jonathanmetzman commented on projects/requests/fuzz_server.py
> +# Copyright 2020 Google LLC
2021

2021-01-05 17:38 UTC, jonathanmetzman commented
We'll accept this project if upstream approves.

2021-01-05 19:27 UTC, catenacyber commented
cc @nateprewitt

2021-01-05 19:52 UTC, nateprewitt commented
Thanks for the cc, @catenacyber. I took a look over the repo and wanted to quickly confirm my understanding. Are there any requirements or implications on Requests beyond receiving fuzz reports?

2021-01-05 20:38 UTC, catenacyber commented
> Are there any requirements or implications on Requests beyond receiving fuzz reports?

For the reports (if any bug is found), would you like me to add more people ?

I do not think there are requirements, but there are some advices.
It is recommended to have the fuzz targets (ie fuzz_server.py) in the upstream repository.
Should I make a PR to add it in a tests/fuzz subdirectory ?

This is an initial integration.
After that, you can (if you want) improve it in multiple ways, cf https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/
I would recommend the use of CIFuzz to get every Pull Request tested with fuzzing cf https://google.github.io/oss-fuzz/getting-started/continuous-integration/

2021-02-02 20:10 UTC, inferno-chromium requested changes

2021-02-02 20:10 UTC, inferno-chromium commented on projects/requests/Dockerfile
> +WORKDIR $SRC/
This needs to be $SRC/requests

2021-02-02 20:10 UTC, inferno-chromium commented on projects/requests/build.sh
> +cd requests
Not needed.

2021-02-02 20:10 UTC, inferno-chromium commented on projects/requests/build.sh
> +# TODO move in upstream repo
no need to add todo here.

2021-02-05 09:22 UTC, catenacyber commented on projects/requests/build.sh
> +cd requests
ok

2021-02-05 09:22 UTC, catenacyber commented on projects/requests/Dockerfile
> +WORKDIR $SRC/
ok

2021-02-05 09:22 UTC, catenacyber commented on projects/requests/build.sh
> +# TODO move in upstream repo
ok

2021-02-15 12:56 UTC, catenacyber commented
@nateprewitt do you have more questions ?
Are you interested in the continuous fuzzing of requests by oss-fuzz ?

2022-04-05 09:21 UTC, DavidKorczynski commented
@catenacyber could you perhaps re-open this PR and put yourself as primary contact and me as an auto_ccs?

2022-04-06 20:08 UTC, catenacyber commented
@DavidKorczynski like that ?

2022-04-06 20:16 UTC, DavidKorczynski commented
> @DavidKorczynski like that ?

Yeah exactly, thanks! Could you also get the CI passing? See here what I had to do for taking an old Python PR into 2022: https://github.com/google/oss-fuzz/pull/4908/commits/f2bbb7b428acef3faf74e84486dd97a3d9e0bb78

2022-04-06 20:18 UTC, DavidKorczynski commented
I think coverage is failing because of this just-merged PR: https://github.com/google/oss-fuzz/pull/7298

i.e. we can use `compile_python_fuzzer` to compile fuzzers now which will also fix coverage, but am not sure if the base image is updated yet.

2022-04-06 20:51 UTC, DavidKorczynski approved these changes
Thanks @catenacyber -- lgtm, I can assist with coverage in the coming days

2022-04-28 18:48 UTC, DavidKorczynski commented
@oliverchang ping

2022-04-28 18:57 UTC, DavidKorczynski reviewed
I think the CI passes if you change:
```
  fuzzer_basename=$(basename -s .py $fuzzer)
  fuzzer_package=${fuzzer_basename}.pkg
  pyinstaller --distpath $OUT --onefile --name $fuzzer_package $fuzzer

  # Create execution wrapper.
  echo "#!/bin/sh
# LLVMFuzzerTestOneInput for fuzzer detection.
this_dir=\$(dirname \"\$0\")
ASAN_OPTIONS=\$ASAN_OPTIONS:symbolize=1:external_symbolizer_path=\$this_dir/llvm-symbolizer:detect_leaks=0 \
\$this_dir/$fuzzer_package \$@" > $OUT/$fuzzer_basename
  chmod u+x $OUT/$fuzzer_basename
```
to 
```
compile_python_fuzzer $fuzzer
```

2022-05-03 06:04 UTC, oliverchang approved these changes

2022-05-03 08:54 UTC, DavidKorczynski commented
@inferno-chromium could you update your request for changes so the PR is approved?

2022-05-06 00:39 UTC, merged