Prometheus: Move oss-fuzz downstream
google/oss-fuzz pull request #5142
Opened 2021-02-09 17:13 UTC by roidelapluie

Pending https://github.com/prometheus/prometheus/pull/8464

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

2021-02-09 17:22 UTC, inferno-chromium requested changes
Please verify your changes locally using 
https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-build-failures

2021-02-09 17:22 UTC, inferno-chromium commented on projects/prometheus/Dockerfile
> -RUN go get github.com/prometheus/prometheus/cmd/...
You forgot to add git clone to your repo :)

2021-02-09 21:22 UTC, roidelapluie commented
I am wondering how I can either clone master or clone the pull request being built (fir cifuzz)

2021-02-10 06:20 UTC, inferno-chromium commented
> I am wondering how I can either clone master or clone the pull request being built (for cifuzz)

cifuzz uses github actions, so it auto uses the pull request code, no need to clone, just need to clone this for oss-fuzz in Dockerfile. see https://google.github.io/oss-fuzz/getting-started/continuous-integration/

2021-02-13 20:08 UTC, closed without merging