[Pillow] Defer to pillow repo for build
google/oss-fuzz pull request #5522
Opened 2021-03-28 14:13 UTC by wiredfool

* Move build.sh, dictionary creation in to Pillow
* fuzz_pillow is now in Pillow's repo.

Pillow now (https://github.com/python-pillow/Pillow/pull/5328) hosts the build.sh, existing fuzzer, the new font fuzzer, and dictionary creation scripts. This also fixes the current build issue.

2021-03-28 16:41 UTC, inferno-chromium approved these changes

2021-04-03 03:03 UTC, inferno-chromium requested changes
This CL needs a rebase, there is some conflict.

2021-04-03 15:27 UTC, wiredfool commented
It looks like someone basically did the same thing as my closed #5521 and got in ahead of this and caused the conflict.

2021-04-03 16:45 UTC, inferno-chromium approved these changes

2021-04-03 16:45 UTC, merged