Build HDF5 1.12.1 for matio
google/oss-fuzz pull request #6018
Opened 2021-07-09 17:51 UTC by tbeu

2021-07-10 02:00 UTC, inferno-chromium requested changes
This is failing all over CI.

```
chmod 644 /work/include/zlib.h /work/include/zconf.h
/src/matio
/src /src/matio
tar: hdf5-1.12.0.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Building fuzzers failed.
Running: docker build -t gcr.io/oss-fuzz/matio projects/matio
Keeping existing build artifacts as-is (if any).```

2021-07-26 18:10 UTC, tbeu commented
Ready to merge?

2021-07-26 18:15 UTC, DavidKorczynski approved these changes

2021-08-14 05:03 UTC, inferno-chromium approved these changes

2021-08-14 05:03 UTC, merged