net-snmp: Simplify the build scripts
google/oss-fuzz pull request #6231
Opened 2021-08-16 20:13 UTC by bvanassche

2021-08-17 19:00 UTC, asraa requested changes
Other than that lgtm, thanks!

2021-08-20 14:15 UTC, asraa commented
Can you repro the failure locally? Seems like you're debugging the compiler flags

2021-08-28 14:46 UTC, inferno-chromium commented
```checking for Perl cc... x86_64-linux-gnu-gcc
checking whether x86_64-linux-gnu-gcc is a GNU C compiler... no
configure: error: This build is using a GNU C compiler (clang) while Perl has been compiled with a non-GNU (or non-working) compiler (x86_64-linux-gnu-gcc). This likely won't work for building with Perl support. Either specify a different compiler (--with-cc=PATH), disable this check (--disable-perl-cc-checks) or build without Perl (--without-perl-modules).
ERROR:root:Building fuzzers failed.
Building project net-snmp
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_fuzzers net-snmp --engine libfuzzer --sanitizer address --architecture x86_64
Failed projects: net-snmp
Error: Process completed with exit code 1.
```

2021-08-28 21:34 UTC, bvanassche commented
> Can you repro the failure locally? Seems like you're debugging the compiler flags

I have no idea yet what causes the build failure. I will try to reproduce the build failure locally when I have the time to do so.

2021-08-28 21:40 UTC, bvanassche commented
> ```
> checking whether x86_64-linux-gnu-gcc is a GNU C compiler... no
> configure: error: This build is using a GNU C compiler (clang) while Perl has been compiled with a non-GNU (or non-working) compiler (x86_64-linux-gnu-gcc). This likely won't work for building with Perl support. Either specify a different compiler (--with-cc=PATH), disable this check (--disable-perl-cc-checks) or build without Perl (--without-perl-modules).
> ERROR:root:Building fuzzers failed.
> Building project net-snmp
> Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_fuzzers net-snmp --engine libfuzzer --sanitizer address --architecture x86_64
> Failed projects: net-snmp
> Error: Process completed with exit code 1.
> ```

Thanks, this explains at least one of the build failures. Let's try to disable the Net-SNMP Perl extensions ...

2021-08-29 17:53 UTC, DavidKorczynski commented
We still get the same error:
```
checking if we are in the source tree so we can install Perl modules... Yes
checking for Perl cc... x86_64-linux-gnu-gcc
checking whether x86_64-linux-gnu-gcc is a GNU C compiler... no
configure: error: This build is using a GNU C compiler (clang) while Perl has been compiled with a non-GNU (or non-working) compiler (x86_64-linux-gnu-gcc). This likely won't work for building with Perl support. Either specify a different compiler (--with-cc=PATH), disable this check (--disable-perl-cc-checks) or build without Perl (--without-perl-modules).
ERROR:root:Building fuzzers failed.
```

2021-08-29 18:37 UTC, bvanassche commented
> We still get the same error:
> 
> ```
> checking if we are in the source tree so we can install Perl modules... Yes
> checking for Perl cc... x86_64-linux-gnu-gcc
> checking whether x86_64-linux-gnu-gcc is a GNU C compiler... no
> configure: error: This build is using a GNU C compiler (clang) while Perl has been compiled with a non-GNU (or non-working) compiler (x86_64-linux-gnu-gcc). This likely won't work for building with Perl support. Either specify a different compiler (--with-cc=PATH), disable this check (--disable-perl-cc-checks) or build without Perl (--without-perl-modules).
> ERROR:root:Building fuzzers failed.
> ```

I'm considering to modify the Net-SNMP configure script such that it checks for ABI compatibility and hence accepts building Net-SNMP with clang in combination with a Perl interpreter built with gcc.

2021-08-29 18:40 UTC, DavidKorczynski commented
> > We still get the same error:
> > ```
> > checking if we are in the source tree so we can install Perl modules... Yes
> > checking for Perl cc... x86_64-linux-gnu-gcc
> > checking whether x86_64-linux-gnu-gcc is a GNU C compiler... no
> > configure: error: This build is using a GNU C compiler (clang) while Perl has been compiled with a non-GNU (or non-working) compiler (x86_64-linux-gnu-gcc). This likely won't work for building with Perl support. Either specify a different compiler (--with-cc=PATH), disable this check (--disable-perl-cc-checks) or build without Perl (--without-perl-modules).
> > ERROR:root:Building fuzzers failed.
> > ```
> 
> I'm considering to modify the Net-SNMP configure script such that it checks for ABI compatibility and hence accepts building Net-SNMP with clang in combination with a Perl interpreter built with gcc.

Alternatively we could keep calls to `configure` and `make` here, and then call directly into `build-fuzz-tests.sh` from the build script here too - thus avoid calling `ci/build.sh`?

2021-08-29 19:43 UTC, DavidKorczynski approved these changes
LGTM, thanks a lot @bvanassche!

2021-08-29 19:45 UTC, bvanassche commented
@ArashPartow , please take another look now that the build failures have been fixed.

2021-08-30 03:47 UTC, inferno-chromium commented on projects/net-snmp/build.sh
> +export CC CXX CFLAGS CXXFLAGS SRC WORK OUT LIB_FUZZING_ENGINE
can you just remove lines 19-21

2021-08-30 22:48 UTC, merged