gdbm: initial integration
google/oss-fuzz pull request #6258
Opened 2021-08-20 14:20 UTC by graygnuorg

2021-08-20 14:29 UTC, graygnuorg commented
@googlebot I signed it!

2021-08-28 14:45 UTC, inferno-chromium requested changes
```
Changed files: projects/gdbm/project.yaml
Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/gdbm/project.yaml: main_repo section is missing.
Failed.
Error: Process completed with exit code 1.
```

2021-08-28 16:49 UTC, DavidKorczynski commented
@graygnuorg the `project.yaml` file alone won't enable fuzzing: are you also intending on including a `Dockerfile`, `build.sh` and fuzzers (preferably those should be in the gdbm repository) in this PR?

2021-08-30 19:36 UTC, inferno-chromium commented
will let @AdamKorcz @DavidKorczynski review and merge/suggest changes.

2021-08-31 11:59 UTC, DavidKorczynski commented on projects/gdbm/build.sh
> +for format in standard numsync; do
The build script gets a bit bloated IMHO having the seeds like this - would it make sense to make them explicit and place them in the repository here? https://git.gnu.org.ua/gdbm.git/tree/fuzz?h=fuzz

2021-08-31 12:11 UTC, DavidKorczynski requested changes
Looks good but what about moving the seeds to the upstream repo? Following that then this looks good to me.

2021-08-31 14:08 UTC, DavidKorczynski approved these changes

2021-08-31 14:08 UTC, DavidKorczynski commented on projects/gdbm/build.sh
> +
Nit: 3 blank lines here

2021-08-31 14:15 UTC, DavidKorczynski approved these changes

2021-09-01 12:19 UTC, DavidKorczynski commented
@graygnuorg please remove the blanks lines highlighted above and I will merge this in.

2021-09-01 13:11 UTC, DavidKorczynski approved these changes
LGTM. Thanks @graygnuorg 

@inferno-chromium I think you will have to merge this one is as you requested changes (I can't merge because of that).

2021-09-01 14:26 UTC, inferno-chromium approved these changes

2021-09-01 14:26 UTC, merged