Stop using proto constants named DO_NOT_USE
google/oss-fuzz pull request #6512
Opened 2021-09-22 19:54 UTC by jorgbrown

Proto team is in the process of renaming these constants because so many users are attempting to handle them in switch statements, rather than adding a "default" case in the switch statement.  Switch early to avoid breakage.

2021-09-22 20:22 UTC, DavidKorczynski commented
Thanks @jorgbrown - I'm not quite able to determine your relationship with xerces-c, which is the project you modified. Could you clarify a bit or perhaps get a maintainer to confirm, e.g. anyone from here https://github.com/apache/xerces-c?

2021-09-22 20:34 UTC, DavidKorczynski requested changes
Thanks @jorgbrown - I'm not quite able to determine your relationship with xerces-c, which is the project you modified. Could you clarify a bit or perhaps get a maintainer to confirm, e.g. anyone from here https://github.com/apache/xerces-c?

2021-11-06 19:21 UTC, ryihan commented
Apache Xerces C++ 
https://svn.apache.org/viewvc/xerces/c/

2021-11-06 19:22 UTC, ryihan commented
> Apache Xerces C++ https://svn.apache.org/viewvc/xerces/c/
release-procedure...
https://svn.apache.org/viewvc/xerces/c/admin/release-procedure.txt?view=log

2023-02-10 21:00 UTC, closed without merging