fix openh264 folder rename issue
google/oss-fuzz pull request #7830
Opened 2022-06-09 03:39 UTC by huili2

att. 
Change the test code to re-enable the fuzzy test for openh264.

2022-06-09 09:30 UTC, DavidKorczynski commented
The CI is complaining about a missing header file in https://github.com/google/oss-fuzz/blob/master/projects/openh264/decoder_fuzzer.cpp -- would it perhaps be possible to move the fuzzer upstream?

2022-06-14 01:35 UTC, huili2 commented
anybody could have a look if my second commit fixed the issue? Thanks.

2022-06-17 21:14 UTC, DavidKorczynski requested changes

2022-06-17 21:14 UTC, DavidKorczynski commented on projects/openh264/decoder_fuzzer.cpp
> +# Copyright 2021 Google LLC
Many apologies for the delay here! Could you do a minor nit and change this to 2022? After that we can merge this.

2022-06-17 21:14 UTC, DavidKorczynski commented on projects/openh264/decoder_fuzzer.cpp
> +# Copyright 2021 Google LLC
ah sorry - you moved the file instead of adding  -- I'll merge this in.

2022-06-17 21:15 UTC, DavidKorczynski approved these changes

2022-06-17 21:15 UTC, merged