[coturn] initial integration
google/oss-fuzz pull request #8239
Opened 2022-08-13 09:42 UTC by 0x34d

Hello @misi 
For More Security Related issues in the @coturn interface, The ```coturn``` project can in deployed in ```oss-fuzz``` infrastructure.
I and ```oss-fuzz``` team would like to hear your thoughts on integration.

Signed-off-by: 0x34d <ajsinghyadav00@gmail.com>

2022-08-17 16:25 UTC, jonathanmetzman commented
We are happy to accept this project if upstream wants it integrated.

2022-08-24 06:39 UTC, 0x34d commented
@bradleythughes ping.

2022-08-24 06:50 UTC, 0x34d commented
@ggarber @bradleythughes @tyranron ping. 
Any Comment?

2022-09-18 00:08 UTC, jonathanmetzman requested changes
lgtm other than the zips, please fix

2022-09-18 00:08 UTC, jonathanmetzman commented on projects/coturn/build.sh
> +cp input/FuzzStun_seed_corpus.zip $OUT/FuzzStun_seed_corpus.zip
Please download the zips from some place else.

2022-09-18 10:48 UTC, jonathanmetzman commented on projects/coturn/project.yaml
> +  - "mom040267@gmail.com"
Upstream is auto_cc, you are either.

2022-09-18 10:49 UTC, jonathanmetzman approved these changes
lgtm

2022-09-18 10:49 UTC, merged