Copy all fuzzers into SRC so they can be built
google/oss-fuzz pull request #8496
Opened 2022-09-14 16:12 UTC by jduart

build.sh is taking all the *_fuzzer.cc files and builds them as targets, but the Dockerfile was not updated to copy the new fuzzers.

2022-09-15 00:20 UTC, oliverchang approved these changes

2022-09-15 00:20 UTC, oliverchang requested changes
Thanks! This looks good, but it looks like the compilation is failing:

```
/usr/bin/ld: wasm_objdump_fuzzer.cc:(.text.LLVMFuzzerTestOneInput[LLVMFuzzerTestOneInput]+0x3f8): undefined reference to `wabt::ReadBinaryObjdump(unsigned char const*, unsigned long, wabt::ObjdumpOptions*, wabt::ObjdumpState*)'
/usr/bin/ld: wasm_objdump_fuzzer.cc:(.text.LLVMFuzzerTestOneInput[LLVMFuzzerTestOneInput]+0x428): undefined reference to `wabt::ReadBinaryObjdump(unsigned char const*, unsigned long, wabt::ObjdumpOptions*, wabt::ObjdumpState*)'
/usr/bin/ld: wasm_objdump_fuzzer.cc:(.text.LLVMFuzzerTestOneInput[LLVMFuzzerTestOneInput]+0x458): undefined reference to `wabt::ReadBinaryObjdump(unsigned char const*, unsigned long, wabt::ObjdumpOptions*, wabt::ObjdumpState*)'
/usr/bin/ld: wasm_objdump_fuzzer.cc:(.text.LLVMFuzzerTestOneInput[LLVMFuzzerTestOneInput]+0x488): undefined reference to `wabt::ReadBinaryObjdump(unsigned char const*, unsigned long, wabt::ObjdumpOptions*, wabt::ObjdumpState*)'
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

https://github.com/google/oss-fuzz/actions/runs/3054361755/jobs/4926524506

2022-09-15 17:19 UTC, jduart commented
Talking with Julien about this. Should I remove this PR while we work on this?

2022-09-16 00:59 UTC, oliverchang commented
> Talking with Julien about this. Should I remove this PR while we work on this?

We can just keep it open and wait for the build issue fixes to land first.

2022-09-19 01:54 UTC, oliverchang approved these changes

2022-09-19 01:55 UTC, merged