Keep libclang in Docker images
google/oss-fuzz pull request #9317
Opened 2022-12-30 13:30 UTC by Tpt

Allows to easily fuzz Rust projects that rely on the bindgen crate that itself depends on libclang: https://crates.io/crates/bindgen

2023-01-02 19:24 UTC, jonathanmetzman requested changes
I'm afraid this can't be landed until we know how much size this adds to the docker images.
Removing these libraries along with others reduced the image size by almost a GB: https://github.com/google/oss-fuzz/pull/5282
If this adds all or most of this size back we can't land it. Please rebuild the image and find this out for us.

2023-01-02 19:25 UTC, jonathanmetzman commented
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

2023-01-02 19:25 UTC, jonathanmetzman commented
Actually I can find out from our test infra how much this adds. Let me get back to you tomorrow.

2023-01-03 16:43 UTC, jonathanmetzman commented
> Actually I can find out from our test infra how much this adds. Let me get back to you tomorrow.

I think this increases the image size from 300 MB to 390 MB. Can we come up with an alternative? What happens if we don't merge this?

2023-01-03 16:52 UTC, jonathanmetzman commented
> > Actually I can find out from our test infra how much this adds. Let me get back to you tomorrow.
> 
> I think this increases the image size from 300 MB to 390 MB. Can we come up with an alternative? What happens if we don't merge this?

This is compressed size btw

2023-01-03 20:58 UTC, Tpt commented
@jonathanmetzman Thank you for investigating. I believe I should come up with the way of making it work by installing libclang during the build process. It's probably better than having a nearly 25% bigger image. Thank you again!

2023-01-03 20:58 UTC, closed without merging

2023-01-03 21:28 UTC, jonathanmetzman commented
> @jonathanmetzman Thank you for investigating. I believe I should come up with the way of making it work by installing libclang during the build process. It's probably better than having a nearly 25% bigger image. Thank you again!

No worries! Thank you for trying this. Sorry if my initial response was a bit aggressive.

2023-01-04 18:03 UTC, Tpt commented
> Sorry if my initial response was a bit aggressive.

I have not felt it this way :). I have manage to integrate ClusterFuzzLite in my project: https://github.com/oxigraph/oxigraph/pull/337 Thank you for this amazing tool!

2023-01-06 03:12 UTC, jonathanmetzman commented
No worries. Definitely reach out if you have any issues. I will do my best to help!
Thank you for the kind words.