croaring: Moves fuzz harnesses upstream
google/oss-fuzz pull request #9861
Opened 2023-03-04 18:46 UTC by silvergasp

This PR is to be paired with RoaringBitmap/CRoaring#442, which takes the files removed here and adds them to upstream CRoaring.

2023-03-04 18:48 UTC, silvergasp commented
cc @lemire @DavidKorczynski, continuing on from the conversation here https://github.com/google/oss-fuzz/pull/9859#issuecomment-1454789377. Note that this change will not pass the CI until https://github.com/RoaringBitmap/CRoaring/pull/442 is merged.

2023-03-04 22:30 UTC, lemire commented
https://github.com/RoaringBitmap/CRoaring/pull/442 merged….

2023-03-04 22:43 UTC, DavidKorczynski requested changes

2023-03-04 22:43 UTC, DavidKorczynski commented on projects/croaring/Dockerfile
> +COPY fuzz/croaring_fuzzer.c \
No need for this COPY now

2023-03-05 00:01 UTC, DavidKorczynski approved these changes

2023-03-05 00:01 UTC, merged